[versions]
accompanist = "0.36.0"
activityCompose = "1.10.1"
agp = "8.13.0"
androidxBaselineprofile = "1.4.0"
androidxHiltCompiler = "1.2.0"
androidxCoreSplashscreen = "1.0.1"
androidxTestCore = "1.7.0"
androidxTestRules = "1.7.0"
androidxWorkManager = "2.10.3"
appcompat = "1.7.1"
autoValue = "1.11.0"
benchmark = "1.4.0"
composeBom = "2025.08.01"
composeConstraintlayout = "1.1.1"
composeNavigation = "2.9.3"
coreKtx = "1.17.0"
coroutinesTest = "1.10.2"
credentials = "1.5.0"
dataStore = "1.1.7"
espressoCore = "3.7.0"
firebase = "34.2.0"
googleFirebaseAppdistribution = "5.1.1"
googleGmsGoogleServices = "4.4.3"
googleId = "1.1.1"
hiltNavigationVersion = "1.2.0"
hiltVersion = "2.57.1"
hiltWorkManager = "1.2.0"
junit = "4.13.2"
junitVersion = "1.3.0"
konsist = "0.17.3"
kotlin = "2.2.10"
kotlinCoroutines = "1.10.2"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxSerializationJson = "1.9.0"
kspPluginVersion = "2.2.10-2.0.2"
ktlint = "12.3.0"
lifecycleRuntimeKtx = "2.9.3"
lottie = "6.4.1"
material = "1.13.0"
mockk = "1.14.5"
moshi = "1.15.2"
moshiConverter = "3.0.0"
navigation = "2.9.3"
navigationSuiteAndroid = "1.3.2"
okHttp = "5.1.0"
profileinstaller = "1.4.1"
retrofit = "3.0.0"
room = "2.8.0"
runtime-tracing = "1.9.0"
timber = "5.0.1"
turbine = "1.2.1"
tracing-ktx = "1.3.0"
tracing-perfetto = "1.0.0"
recyclerview = "1.4.0"
uiautomator = "2.3.0"
firebaseCrashlytics = "20.0.1"
googleFirebaseCrashlytics = "3.0.6"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation-fragmentKtx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
navigation-suite-android = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite-android", version.ref = "navigationSuiteAndroid" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

accompanist-swipeToDismiss = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }

auto-value-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "autoValue" }
auto-value = { module = "com.google.auto.value:auto-value", version.ref = "autoValue" }

kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

room = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-kotlinKtx = { module = "androidx.room:room-ktx", version.ref = "room" }

dataStore = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore"}

moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlinCodeGen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
moshi-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "moshiConverter" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHiltCompiler" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationVersion" }

work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWorkManager" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorkManager" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }

credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-playService-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
identity-googleId = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleId" }

performance-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
# classpath dependencies
ktlint-gradlePlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }

# test dependencies
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-androidx-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
test-androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
test-androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
test-compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
test-compose-ui-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
test-androidx-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
test-room = { module = "androidx.room:room-testing", version.ref = "room" }
test-hilt = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hiltVersion"}
test-konsist = { group = "com.lemonappdev", name = "konsist", version.ref = "konsist"}
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
test-androidx-work = { module = "androidx.work:work-testing", version.ref = "androidxWorkManager" }
test-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark" }

test-performance-tracing-perfetto = { module = "androidx.tracing:tracing-perfetto", version.ref = "tracing-perfetto" }
test-performance-tracing-perfetto-binary = { module = "androidx.tracing:tracing-perfetto-binary", version.ref = "tracing-perfetto" }
test-performance-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "runtime-tracing" }
test-performance-tracingKtx = { module = "androidx.tracing:tracing-ktx", version.ref = "tracing-ktx" }
test-androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidxBaselineprofile" }
google-firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "googleFirebaseAppdistribution" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPluginVersion" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }


